name: neurotech
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - glib=2.86.1
  - glib-tools=2.86.1
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - icu=75.1
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang13=21.1.5
  - libexpat=2.7.1
  - libffi=3.5.2
  - libglib=2.86.1
  - libhwloc=2.12.1
  - libiconv=1.18
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libogg=1.3.5
  - libpng=1.6.50
  - libsqlite=3.51.0
  - libvorbis=1.3.7
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.5
  - mkl=2025.3.0
  - numpy=2.3.4
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pip=25.2
  - ply=3.11
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pyqtgraph=0.13.7
  - python=3.14.0
  - python_abi=3.14
  - qt-main=5.15.15
  - sip=6.10.0
  - tbb=2022.3.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - tzdata=2025b
  - ucrt=10.0.26100.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vcomp14=14.44.35208
  - zstd=1.5.7
  - pip:
      - brainflow==5.19.0
      - setuptools==80.9.0
prefix: C:\Users\dnxjc\miniforge3\envs\neurotech
